# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MBbOWUykHWv1V9JLLdxhwnHa34mNDr3L

# Mind Reader Bot
"""

def create_cards():
    cards = [
        [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63],
        [2, 3, 6, 7, 10, 11, 14, 15, 18, 19, 22, 23, 26, 27, 30, 31, 34, 35, 38, 39, 42, 43, 46, 47, 50, 51, 54, 55, 58, 59, 62, 63],
        [4, 5, 6, 7, 12, 13, 14, 15, 20, 21, 22, 23, 28, 29, 30, 31, 36, 37, 38, 39, 44, 45, 46, 47, 52, 53, 54, 55, 60, 61, 62, 63],
        [8, 9, 10, 11, 12, 13, 14, 15, 24, 25, 26, 27, 28, 29, 30, 31, 40, 41, 42, 43, 44, 45, 46, 47, 56, 57, 58, 59, 60, 61, 62, 63],
        [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63],
        [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]
    ]

    card_numbers = [1, 2, 4, 8, 16, 32]

    return cards, card_numbers

def main():
    cards, card_numbers = create_cards()

    print("List of cards:")
    for i, card in enumerate(cards, start=1):
        print(f"Card {i} (Number {card_numbers[i-1]}): {card}")

    print("\nThink of a number between 1 and 63.")
    input("Type 'start' when you are ready and hit the 'Enter' key.")

    num = 0
    valid_entries = ['yes', 'no']

    for i, card in enumerate(cards, start=1):
        print(f"\nCard {i} (Number {card_numbers[i-1]}): {card}")
        response = input("Does the number you thought of exist on this card? (yes/no): ").lower()

        while response not in valid_entries:
            print("Invalid entry. Please enter 'yes' or 'no'.")
            response = input("Does the number you thought of exist on this card? (yes/no): ").lower()

        if response == 'yes':
            num += card_numbers[i-1]

    print(f"\nThe computer's guess is: {num}")

if __name__ == "__main__":
    main()